#!/usr/bin/env python3
from __future__ import annotations

import argparse
import re
import subprocess
from datetime import datetime
from pathlib import Path
from zoneinfo import ZoneInfo

REPO = "miumiupy98-art/miuread-koreader"
BETA_MANIFEST = f"https://github.com/{REPO}/releases/download/beta-channel/update-beta.json"
STABLE_MANIFEST = f"https://github.com/{REPO}/releases/download/stable-channel/update.json"
MAX_CHANGELOG_BULLETS = 20


def run(*args: str, check: bool = True) -> str:
    proc = subprocess.run(args, text=True, capture_output=True)
    if check and proc.returncode != 0:
        raise subprocess.CalledProcessError(proc.returncode, args, proc.stdout, proc.stderr)
    return proc.stdout.strip()


def replace_one(text: str, pattern: str, replacement: str, label: str, flags: int = 0) -> str:
    updated, count = re.subn(pattern, replacement, text, count=1, flags=flags)
    if count != 1:
        raise SystemExit(f"无法唯一更新 {label}（匹配到 {count} 处）")
    return updated


def parse_beta(value: str):
    m = re.fullmatch(r"(\d+)\.(\d+)\.(\d+)-beta\.(\d+)", value)
    return tuple(map(int, m.groups())) if m else None


def parse_stable(value: str):
    m = re.fullmatch(r"(\d+)\.(\d+)\.(\d+)", value)
    return tuple(map(int, m.groups())) if m else None


def previous_tag(channel: str, current_tag: str, version: str) -> str | None:
    parser = parse_beta if channel == "beta" else parse_stable
    current = parser(version)
    if current is None:
        return None
    candidates: list[tuple[tuple[int, ...], str]] = []
    for tag in run("git", "tag", "--list").splitlines():
        tag = tag.strip()
        if not tag or tag == current_tag or not tag.startswith("v"):
            continue
        parsed = parser(tag[1:])
        if parsed is not None and parsed < current:
            candidates.append((parsed, tag))
    return max(candidates)[1] if candidates else None


def clean_subject(subject: str) -> str | None:
    subject = re.sub(r"\s+", " ", subject).strip()
    if not subject:
        return None
    # 发布机制自己产生的提交不进入下一版说明。
    if re.fullmatch(r"同步 (?:Beta|正式) 版本至 .+", subject):
        return None
    if re.fullmatch(r"同步Beta版本至 .+", subject):
        return None
    # 普通 merge 提交只描述合并动作，不描述用户实际得到的变化。
    if re.match(r"(?i)^merge(?: branch| pull request| remote-tracking branch)?\b", subject):
        return None
    return subject


def commit_affects_plugin(sha: str) -> bool:
    """Only user-facing plugin changes belong in autogenerated release notes.

    Repository-maintenance commits that touch only .github/, README, or other
    release infrastructure stay in git history but are omitted from device
    update notes.
    """
    paths = run(
        "git", "diff-tree", "--no-commit-id", "--name-only", "-r", sha, check=False
    ).splitlines()
    return any(path.strip().startswith("miuread.koplugin/") for path in paths)


def log_subjects(rev: str, allowed_shas: set[str] | None = None) -> list[str]:
    output = run("git", "log", "--reverse", "--no-merges", "--format=%H%x09%s", rev, check=False)
    bullets: list[str] = []
    seen: set[str] = set()
    for line in output.splitlines():
        if "\t" not in line:
            continue
        sha, subject = line.split("\t", 1)
        if allowed_shas is not None and sha not in allowed_shas:
            continue
        if not commit_affects_plugin(sha):
            continue
        subject = clean_subject(subject)
        if not subject or subject in seen:
            continue
        seen.add(subject)
        bullets.append(subject)
        if len(bullets) >= MAX_CHANGELOG_BULLETS:
            break
    return bullets


def beta_bullets(current_tag: str, version: str) -> list[str]:
    prev = previous_tag("beta", current_tag, version)
    rev = f"{prev}..HEAD" if prev else "HEAD"
    bullets = log_subjects(rev)
    if bullets:
        return bullets
    return [f"内测版本更新至 {version}，功能内容与当前 beta 分支一致。"]


def stable_unique_shas(prev: str) -> set[str]:
    """Return commits in HEAD whose patch is not already present in prev stable.

    git cherry compares patch-ids, so a Beta fix that was previously cherry-picked
    into the stable branch is marked '-' and will not be repeated in the next
    stable release notes even if the Beta history is merged later.
    """
    output = run("git", "cherry", prev, "HEAD", check=False)
    unique: set[str] = set()
    for line in output.splitlines():
        line = line.strip()
        if not line.startswith("+ "):
            continue
        parts = line.split()
        if len(parts) >= 2:
            unique.add(parts[1])
    return unique


def stable_bullets(current_tag: str, version: str) -> list[str]:
    prev = previous_tag("stable", current_tag, version)
    if prev:
        unique = stable_unique_shas(prev)
        bullets = log_subjects(f"{prev}..HEAD", allowed_shas=unique)
        if bullets:
            return bullets
        # git cherry 对极少数历史形态可能无法给出可读提交；保底仍从差异历史取标题。
        bullets = log_subjects(f"{prev}..HEAD")
        if bullets:
            return bullets
    else:
        bullets = log_subjects("HEAD")
        if bullets:
            return bullets
    return [f"正式版本更新至 {version}，功能内容与当前 main 分支一致。"]


def changelog_bullets(channel: str, current_tag: str, version: str) -> list[str]:
    if channel == "beta":
        return beta_bullets(current_tag, version)
    return stable_bullets(current_tag, version)


def update_config(channel: str, version: str) -> None:
    path = Path("miuread.koplugin/miuread/config.lua")
    text = path.read_text(encoding="utf-8")
    marker = "    UPDATE_CHANNELS = {"
    if marker not in text:
        raise SystemExit("config.lua 缺少 UPDATE_CHANNELS 配置。")
    prefix, suffix = text.split(marker, 1)

    manifest = BETA_MANIFEST if channel == "beta" else STABLE_MANIFEST
    label = "内测通道" if channel == "beta" else "正式通道"

    prefix = replace_one(
        prefix,
        r'(?m)^(\s*VERSION\s*=\s*)["\'][^"\']+["\'](,[ \t]*)$',
        rf'\1"{version}"\2',
        "VERSION",
    )
    prefix = replace_one(
        prefix,
        r'(?m)^(\s*UPDATE_CHANNEL\s*=\s*)["\'][^"\']+["\'](,[ \t]*)$',
        rf'\1"{channel}"\2',
        "UPDATE_CHANNEL",
    )
    prefix = replace_one(
        prefix,
        r'(?m)^(\s*UPDATE_CHANNEL_LABEL\s*=\s*)["\'][^"\']+["\'](,[ \t]*)$',
        rf'\1"{label}"\2',
        "UPDATE_CHANNEL_LABEL",
    )
    prefix = replace_one(
        prefix,
        r'(?m)^(\s*UPDATE_MANIFEST\s*=\s*)["\'][^"\']+["\'](,[ \t]*)$',
        rf'\1"{manifest}"\2',
        "UPDATE_MANIFEST",
    )
    prefix = replace_one(
        prefix,
        r'(?ms)^[ \t]*UPDATE_MANIFESTS[ \t]*=[ \t]*\{\n.*?^[ \t]*\},[ \t]*$',
        '    UPDATE_MANIFESTS = {\n'
        f'        "{manifest}",\n'
        '    },',
        "UPDATE_MANIFESTS",
    )
    path.write_text(prefix + marker + suffix, encoding="utf-8")


def update_meta(version: str) -> None:
    path = Path("miuread.koplugin/_meta.lua")
    text = path.read_text(encoding="utf-8")
    text = replace_one(
        text,
        r'(?m)^(\s*version\s*=\s*)["\'][^"\']+["\'](,[ \t]*)$',
        rf'\1"{version}"\2',
        "_meta.lua version",
    )
    path.write_text(text, encoding="utf-8")


def update_changelog(channel: str, version: str, current_tag: str) -> None:
    path = Path("CHANGELOG.md")
    text = path.read_text(encoding="utf-8")
    if re.search(rf"(?m)^## {re.escape(version)}(?:\s+-\s+.*)?$", text):
        return

    date = datetime.now(ZoneInfo("Asia/Tokyo")).date().isoformat()
    bullets = changelog_bullets(channel, current_tag, version)
    section = f"## {version} - {date}\n\n" + "\n".join(f"- {item}" for item in bullets) + "\n\n"

    # 新版本放在第一个版本记录之前；若顶部保留 Unreleased，则放在其后。
    first_version = re.search(r"(?m)^## \d+\.\d+\.\d+", text)
    top_unreleased = re.search(r"(?m)^## Unreleased[ \t]*$", text)
    if top_unreleased and (first_version is None or top_unreleased.start() < first_version.start()):
        next_heading = re.search(r"(?m)^## ", text[top_unreleased.end():])
        pos = top_unreleased.end() + next_heading.start() if next_heading else len(text)
    elif first_version:
        pos = first_version.start()
    else:
        pos = len(text.rstrip())
        if pos:
            text = text[:pos] + "\n\n" + text[pos:]
            pos += 2
    text = text[:pos] + section + text[pos:]
    path.write_text(text, encoding="utf-8")


def validate_version_order(channel: str, version: str, current_tag: str) -> None:
    parser = parse_beta if channel == "beta" else parse_stable
    expected = parser(version)
    assert expected is not None
    others: list[tuple[tuple[int, ...], str]] = []
    for tag in run("git", "tag", "--list").splitlines():
        tag = tag.strip()
        if not tag or tag == current_tag or not tag.startswith("v"):
            continue
        parsed = parser(tag[1:])
        if parsed is not None:
            others.append((parsed, tag))
    if others:
        latest_parsed, latest_tag = max(others)
        if expected <= latest_parsed:
            raise SystemExit(f"版本号必须高于上一版本：{latest_tag} -> {current_tag}")


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("--channel", choices=("beta", "stable"), required=True)
    parser.add_argument("--version", required=True)
    parser.add_argument("--tag", required=True)
    args = parser.parse_args()

    expected = parse_beta(args.version) if args.channel == "beta" else parse_stable(args.version)
    if expected is None:
        kind = "X.Y.Z-beta.N" if args.channel == "beta" else "X.Y.Z"
        raise SystemExit(f"版本号格式错误，应为 {kind}：{args.version}")
    if args.tag != f"v{args.version}":
        raise SystemExit(f"Tag 与版本号不一致：tag={args.tag}, version={args.version}")

    validate_version_order(args.channel, args.version, args.tag)
    update_config(args.channel, args.version)
    update_meta(args.version)
    update_changelog(args.channel, args.version, args.tag)


if __name__ == "__main__":
    main()
