from pathlib import Path
import sys
root=Path(__file__).resolve().parents[1]
main=(root/'miuread.koplugin/main.lua').read_text(encoding='utf-8')
precise=(root/'miuread.koplugin/miuread/precise_position.lua').read_text(encoding='utf-8')
source=(root/'miuread.koplugin/miuread/source_position.lua').read_text(encoding='utf-8')
posmap=(root/'miuread.koplugin/miuread/annotations/posmap.lua').read_text(encoding='utf-8')
worker=(root/'miuread.koplugin/miuread/legacy/read_report_worker.lua').read_text(encoding='utf-8')
store=(root/'miuread.koplugin/miuread/store.lua').read_text(encoding='utf-8')
config=(root/'miuread.koplugin/miuread/config.lua').read_text(encoding='utf-8')
meta=(root/'miuread.koplugin/_meta.lua').read_text(encoding='utf-8')
ch=(root/'CHANGELOG.md').read_text(encoding='utf-8')
workflow=(root/'.github/workflows/release-beta.yml').read_text(encoding='utf-8')
checks=[]
def ok(cond,msg): checks.append((bool(cond),msg))
ok('VERSION = "5.9.0-beta.19"' in config,'config version beta.19')
ok('version = "5.9.0-beta.19"' in meta,'metadata version beta.19')
ok(ch.startswith('## 5.9.0-beta.19'),'beta.19 changelog first')
ok('SCHEMA = 136' in config,'schema remains 136')
ok('SOURCE_ANCHOR_WORDS = {24, 16, 12}' in precise,'multi-anchor sizes')
ok('anchor_candidates = anchor_candidates' in precise,'captured anchor set')
ok('candidate_reason = tostring(reason or "neighbor")' in precise,'bounded title/neighbor candidates')
ok('local function anchor_variants(anchor)' in source,'source anchor variants')
ok('anchor_coordinate_conflict' in source,'coordinate conflict fail closed')
ok('precision_anchor_recovered' in source,'anchor recovery diagnostic')
ok('{images=false, fresh_context=true}' in source,'beta18 fresh context retained')
ok('function PosMap.locateSource' in posmap,'source-only locator')
ok('SOURCE_IGNORABLE' in posmap and 'soft hyphen' in posmap,'format-only source normalization')
ok('reliable_text_anchor_landing' in main,'reliable text landing state')
ok('not reliable_text_anchor_landing' in main,'no percent override after reliable text landing')
ok('精确章节内位置暂未确认' not in main,'misleading warning removed')
ok('已定位到云端章节附近' in main,'real approximate warning retained')
ok('local refreshed=refresh_remote_anchor(client, book_id, book)' in worker,'ReadReport fresh GET retained')
ok('if disk_epoch>memory_epoch then' in store,'beta17 epoch merge retained')
ok('lua5.1 tools/test_beta19_robust_mapping.lua' in workflow,'beta19 contract in workflow')
ok('python3 tools/verify_590_beta19.py' in workflow,'beta19 verifier in workflow')
test_step=workflow.find('- name: Run Lua syntax checks and release regression verifier')
tag_step=workflow.find('- name: Ensure release tag')
ok(test_step>=0 and tag_step>=0 and test_step<tag_step,'tests before tag creation')
failed=[m for c,m in checks if not c]
for c,m in checks: print(('PASS' if c else 'FAIL')+': '+m)
print(f'checks={len(checks)} failures={len(failed)}')
if failed: sys.exit(1)
